=== fercalonso/testSEW/xml/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (nombre, tipoRuta, tiempoDuracion, agencia, descripcion, personasAdecuadas, lugarInicio, direccionInicio, coordenadasInicio, referencias, recomendacion, hitos, planimetriaKML, altimetriaSVG)>
<!ATTLIST ruta
    id ID #REQUIRED
    medioTransporte CDATA #REQUIRED
    fechaInicio CDATA #IMPLIED
    horaInicio CDATA #IMPLIED
>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipoRuta (#PCDATA)>
<!ELEMENT tiempoDuracion (#PCDATA)>
<!ATTLIST tiempoDuracion
    unidad (horas | dias | semanas) #REQUIRED
>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT personasAdecuadas (#PCDATA)>
<!ELEMENT lugarInicio (#PCDATA)>
<!ELEMENT direccionInicio (#PCDATA)>

<!ELEMENT coordenadasInicio (longitud, latitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ATTLIST referencia
    url CDATA #REQUIRED
>

<!ELEMENT recomendacion (#PCDATA)>

<!ELEMENT hitos (hito+)>
<!ELEMENT hito (nombreHito, descripcionHito, coordenadasHito, distanciaDesdeAnterior, galeriaFotografias, galeriaVideos?)>
<!ATTLIST hito
    id ID #IMPLIED
>
<!ELEMENT nombreHito (#PCDATA)>
<!ELEMENT descripcionHito (#PCDATA)>
<!ELEMENT coordenadasHito (longitud, latitud, altitud)>
<!ELEMENT distanciaDesdeAnterior (#PCDATA)>
<!ATTLIST distanciaDesdeAnterior
    unidad (km | m) #REQUIRED
>
<!ELEMENT galeriaFotografias (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT galeriaVideos (video*)>
<!ELEMENT video (#PCDATA)>

<!ELEMENT planimetriaKML (#PCDATA)>
<!ELEMENT altimetriaSVG (#PCDATA)>

=== fercalonso/testSEW/xml/ruta3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
    <ruta id="ruta3" medioTransporte="A pie" fechaInicio="2025-08-20" horaInicio="19:00">
        <nombre>Ruta Gastronómica por los Chigres</nombre>
        <tipoRuta>Gastronomía y sidra</tipoRuta>
        <tiempoDuracion unidad="horas">2</tiempoDuracion>
        <agencia>Con agencia</agencia>
        <descripcion>Descubre los sabores tradicionales de Grado con una ruta por chigres y
            sidrerías emblemáticas.</descripcion>
        <personasAdecuadas>Mayores de 18 años</personasAdecuadas>
        <lugarInicio>Parque de Arriba</lugarInicio>
        <direccionInicio>Calle Asturias, Grado</direccionInicio>
        <coordenadasInicio>
            <longitud>-6.0632</longitud>
            <latitud>43.3848</latitud>
            <altitud>100</altitud>
        </coordenadasInicio>
        <referencias>
            <referencia url="https://www.lasidreria.es/asturias/grado">La Sidrería</referencia>
            <referencia url="https://www.asturiassingluten.es/rutas-gastronomicas/grado">Asturias
                Sin Gluten</referencia>
        </referencias>
        <recomendacion>10</recomendacion>
        <hitos>
            <hito>
                <nombreHito>Sidrería El Rincón</nombreHito>
                <descripcionHito>Ambiente familiar y buena sidra local acompañada de chorizo a la
                    sidra.</descripcionHito>
                <coordenadasHito>
                    <longitud>-6.0620</longitud>
                    <latitud>43.3847</latitud>
                    <altitud>100</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidad="m">200</distanciaDesdeAnterior>
                <galeriaFotografias>
                    <foto>el_rincon.jpg</foto>
                </galeriaFotografias>
                <galeriaVideos />
            </hito>
            <hito>
                <nombreHito>Casa Pachón</nombreHito>
                <descripcionHito>Tapas asturianas clásicas en un entorno tradicional de chigre.</descripcionHito>
                <coordenadasHito>
                    <longitud>-6.0600</longitud>
                    <latitud>43.3845</latitud>
                    <altitud>101</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidad="m">150</distanciaDesdeAnterior>
                <galeriaFotografias>
                    <foto>casa_pachon.jpg</foto>
                </galeriaFotografias>
                <galeriaVideos />
            </hito>
            <hito>
                <nombreHito>La Cuadra</nombreHito>
                <descripcionHito>Postres caseros y sidra en una sidrería con decoración rural.</descripcionHito>
                <coordenadasHito>
                    <longitud>-6.0585</longitud>
                    <latitud>43.3843</latitud>
                    <altitud>99</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidad="m">180</distanciaDesdeAnterior>
                <galeriaFotografias>
                    <foto>la_cuadra.jpg</foto>
                </galeriaFotografias>
                <galeriaVideos />
            </hito>
        </hitos>
        <planimetriaKML>ruta3.kml</planimetriaKML>
        <altimetriaSVG>ruta3.svg</altimetriaSVG>
    </ruta>
</rutas>

=== fercalonso/testSEW/xml/ruta1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
    <ruta id="ruta1" medioTransporte="A pie" fechaInicio="2025-07-15" horaInicio="10:00">
        <nombre>Ruta de la Arquitectura Indiana</nombre>
        <tipoRuta>Arquitectura y monumentos</tipoRuta>
        <tiempoDuracion unidad="horas">3</tiempoDuracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Una ruta a pie por el centro de Grado para descubrir su arquitectura indiana y
            otros edificios históricos.</descripcion>
        <personasAdecuadas>Se puede ir con niños</personasAdecuadas>
        <lugarInicio>Plaza General Ponte</lugarInicio>
        <direccionInicio>Plaza General Ponte, Grado</direccionInicio>
        <coordenadasInicio>
            <longitud>-6.0656</longitud>
            <latitud>43.3849</latitud>
            <altitud>100</altitud>
        </coordenadasInicio>
        <referencias>
            <referencia url="https://es.wikipedia.org/wiki/Grado_(Asturias)">Wikipedia</referencia>
            <referencia url="https://www.turismoasturias.es/descubre/municipios/grado">Turismo
                Asturias</referencia>
            <referencia url="https://indianos.info/asturias/grado/">Indianos.info</referencia>
        </referencias>
        <recomendacion>8</recomendacion>
        <hitos>
            <hito>
                <nombreHito>Casa de los Arcos</nombreHito>
                <descripcionHito>Ejemplo notable de arquitectura indiana con elementos decorativos
                    originales.</descripcionHito>
                <coordenadasHito>
                    <longitud>-6.0671</longitud>
                    <latitud>43.3845</latitud>
                    <altitud>102</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidad="m">250</distanciaDesdeAnterior>
                <galeriaFotografias>
                    <foto>casa_arcos.jpg</foto>
                </galeriaFotografias>
                <galeriaVideos />
            </hito>
            <hito>
                <nombreHito>Capilla de Los Dolores</nombreHito>
                <descripcionHito>Edificio barroco del siglo XVIII vinculado a la cultura local.</descripcionHito>
                <coordenadasHito>
                    <longitud>-6.0660</longitud>
                    <latitud>43.3830</latitud>
                    <altitud>104</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidad="m">180</distanciaDesdeAnterior>
                <galeriaFotografias>
                    <foto>capilla_dolores.jpg</foto>
                </galeriaFotografias>
                <galeriaVideos />
            </hito>
            <hito>
                <nombreHito>Mercado de Grado</nombreHito>
                <descripcionHito>Uno de los mercados más emblemáticos del occidente asturiano.</descripcionHito>
                <coordenadasHito>
                    <longitud>-6.0667</longitud>
                    <latitud>43.3852</latitud>
                    <altitud>100</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidad="m">300</distanciaDesdeAnterior>
                <galeriaFotografias>
                    <foto>mercado.jpg</foto>
                </galeriaFotografias>
                <galeriaVideos />
            </hito>
            <hito>
                <nombreHito>Ayuntamiento de Grado</nombreHito>
                <descripcionHito>Edificio civil con fachada de estilo ecléctico.</descripcionHito>
                <coordenadasHito>
                    <longitud>-6.0655</longitud>
                    <latitud>43.3850</latitud>
                    <altitud>101</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidad="m">200</distanciaDesdeAnterior>
                <galeriaFotografias>
                    <foto>ayuntamiento.jpg</foto>
                </galeriaFotografias>
                <galeriaVideos />
            </hito>
            <hito>
                <nombreHito>Parque San Antonio</nombreHito>
                <descripcionHito>Pulmón verde del centro urbano con zonas de paseo y descanso.</descripcionHito>
                <coordenadasHito>
                    <longitud>-6.0640</longitud>
                    <latitud>43.3840</latitud>
                    <altitud>98</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidad="m">150</distanciaDesdeAnterior>
                <galeriaFotografias>
                    <foto>parque_san_antonio.jpg</foto>
                </galeriaFotografias>
                <galeriaVideos />
            </hito>
        </hitos>
        <planimetriaKML>ruta1.kml</planimetriaKML>
        <altimetriaSVG>ruta1.svg</altimetriaSVG>
    </ruta>
</rutas>

=== fercalonso/testSEW/xml/ruta2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
    <ruta id="ruta2" medioTransporte="A pie" fechaInicio="2025-08-02" horaInicio="09:00">
        <nombre>Ruta Natural por el Río Cubia</nombre>
        <tipoRuta>Ruta natural</tipoRuta>
        <tiempoDuracion unidad="horas">2.5</tiempoDuracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Un paseo tranquilo por las orillas del río Cubia, con vistas a la naturaleza y
            áreas de descanso.</descripcion>
        <personasAdecuadas>Se puede ir con niños</personasAdecuadas>
        <lugarInicio>Paseo del Río Cubia</lugarInicio>
        <direccionInicio>Calle Río Cubia, Grado</direccionInicio>
        <coordenadasInicio>
            <longitud>-6.0625</longitud>
            <latitud>43.3865</latitud>
            <altitud>95</altitud>
        </coordenadasInicio>
        <referencias>
            <referencia url="https://www.asturiasparadisfrutar.es/rutas/rio-cubia">Asturias para
                disfrutar</referencia>
            <referencia url="https://www.senditur.com/es/ruta/paseo-fluvial-del-rio-cubia/">Senditur</referencia>
        </referencias>
        <recomendacion>9</recomendacion>
        <hitos>
            <hito>
                <nombreHito>Inicio Paseo Fluvial</nombreHito>
                <descripcionHito>Punto de partida del sendero junto al parque infantil.</descripcionHito>
                <coordenadasHito>
                    <longitud>-6.0625</longitud>
                    <latitud>43.3865</latitud>
                    <altitud>95</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidad="m">0</distanciaDesdeAnterior>
                <galeriaFotografias>
                    <foto>inicio_paseo.jpg</foto>
                </galeriaFotografias>
                <galeriaVideos />
            </hito>
            <hito>
                <nombreHito>Zona de merendero</nombreHito>
                <descripcionHito>Área de descanso con mesas y bancos, ideal para picnic.</descripcionHito>
                <coordenadasHito>
                    <longitud>-6.0610</longitud>
                    <latitud>43.3870</latitud>
                    <altitud>96</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidad="m">400</distanciaDesdeAnterior>
                <galeriaFotografias>
                    <foto>merendero.jpg</foto>
                </galeriaFotografias>
                <galeriaVideos />
            </hito>
            <hito>
                <nombreHito>Puente de madera</nombreHito>
                <descripcionHito>Pequeño puente peatonal sobre el río con vistas naturales.</descripcionHito>
                <coordenadasHito>
                    <longitud>-6.0598</longitud>
                    <latitud>43.3875</latitud>
                    <altitud>94</altitud>
                </coordenadasHito>
                <distanciaDesdeAnterior unidad="m">200</distanciaDesdeAnterior>
                <galeriaFotografias>
                    <foto>puente_madera.jpg</foto>
                </galeriaFotografias>
                <galeriaVideos />
            </hito>
        </hitos>
        <planimetriaKML>ruta2.kml</planimetriaKML>
        <altimetriaSVG>ruta2.svg</altimetriaSVG>
    </ruta>
</rutas>
